spring.application.name=aerolinea-api

spring.datasource.url=jdbc:postgresql://localhost:5432/aerolinea_db
spring.datasource.username=postgres
spring.datasource.password=cero

spring.jpa.hibernate.ddl-auto=update
